CREATE DATABASE if not exists quan_li_ban_hang;
USE quan_li_ban_hang ;

CREATE TABLE Customer(
	cID INT AUTO_INCREMENT PRIMARY KEY,
    cNAME VARCHAR(30) NOT NULL,
    cAGE INT CHECK(cAGE BETWEEN 5 AND 80)
);

CREATE TABLE Orders(
	oID INT AUTO_INCREMENT PRIMARY KEY,
    cID INT NOT NULL,
    oDATE DATETIME NOT NULL,
    oTotalPrice INT,
    FOREIGN KEY (cID) REFERENCES Customer (cID)
);
CREATE TABLE Product(
	pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pName VARCHAR(30) NOT NULL,
    pPrice INT 
);

CREATE TABLE OrderDetail(
	oID INT NOT NULL ,
    pID INT NOT NULL,
    odQTY VARCHAR(30),
    PRIMARY KEY (oID,pID),
    FOREIGN KEY (oID) REFERENCES Orders(oID),
    FOREIGN KEY (pID) REFERENCES Product(pID)
); 